# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5QwihPfscVqZqlSUyTpsiDiuOQfPqyY
"""from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, FloatType
from pyspark.sql.functions import col
from pyspark.sql import functions as F


ss = SparkSession.builder.appName("DriverAnalysis").getOrCreate()

schema = StructType([
    StructField("driverID", StringType(), True),
    StructField("carPlateNumber", StringType(), True),
    StructField("Latitude", FloatType(), True),
    StructField("Longtitude ", FloatType(), True),
    StructField("Speed", IntegerType(), True),
    StructField("Direction", IntegerType(), True),
    StructField("siteName ", StringType(), False),
    StructField("Time", StringType(), True),
    StructField("isRapidlySpeedup", IntegerType(), False),
    StructField("isRapidlySlowdown", IntegerType(), False),
    StructField("isNeutralSlide", IntegerType(), False),
    StructField("isNeutralSlideFinished", IntegerType(), False),
    StructField("neutralSlideTime", IntegerType(), False),
    StructField("isOverspeed", IntegerType(), False),
    StructField("isOverspeedFinished", IntegerType(), False),
    StructField("overspeedTime", IntegerType(), False),
    StructField("isFatigueDriving", IntegerType(), False),
    StructField("isHthrottleStop", IntegerType(), False),
    StructField("isOilLeak", IntegerType(), False)
])


#selected_person = "duxu1000009"
startTime = "2017-01-01 08:00:10"
endTime = "2017-01-01 08:05:10"


df = ss.read \
    .option("header", "False") \
    .option("delimiter", ",") \
    .schema(schema) \
    .csv("detail_record_2017_01_02_08_00_00.csv")

df = df.sort("driverID","Time",ascending=True)
df_count = df.groupby("driverID").count()
#df_count.show()


def printPersonInfo(df, driverID):

  

  driverNumber = df.select("driverID").distinct().count()
  #print("Number of Driver: ", driverNumber)


  selected_person_df = df.filter(col("driverID") == driverID)
  selected_person_df = selected_person_df.filter(col("Time") < endTime)
  selected_person_df = selected_person_df.filter(col("Time") > startTime)
  #selected_person_df.show(20)

  car_plate_number = selected_person_df.select("carPlateNumber").collect()[0][0]

  count_overspeed = selected_person_df.filter("isOverSpeed == 1").count() #Total number of overspeeding
  time_overspeed = selected_person_df.agg(F.sum("overspeedTime")).collect()[0][0] #Total Time of overspeeding
  time_overspeed = 0 if not time_overspeed else time_overspeed #change None to 0 if time_overspeed is None


  count_fatigueDriving = selected_person_df.filter("isFatigueDriving == 1").count() #Total number of fatigue driving


  count_neutralSlide = selected_person_df.filter("isNeutralSlide == 1").count() #Total number of neutral slide
  time_neutralSlide = selected_person_df.agg(F.sum("neutralSlideTime")).collect()[0][0]
  time_neutralSlide = 0 if not time_neutralSlide else time_neutralSlide #change None to 0 if time_neutralSlide is None


  count_rapidSpeedUp = selected_person_df.filter("isRapidlySpeedup == 1").count() #Total number of rapid speed up
  count_rapidSlowDown = selected_person_df.filter("isRapidlySlowdown == 1").count() #Total number of rapid slow dowm

  count_hthrottleStop = selected_person_df.filter("isHthrottleStop == 1").count() # Total number of HthrottleStop
  count_oilLeak = selected_person_df.filter("isOilLeak == 1").count() # Total number of oil Leak

  count_dangerEvent = count_overspeed +\
             count_fatigueDriving +\
             count_neutralSlide +\
             count_rapidSlowDown +\
             count_rapidSpeedUp +\
             count_hthrottleStop +\
             count_oilLeak



  print(startTime, "to ",endTime,"\n")
  print("DriverID :", driverID)
  print("carPlateNumber :", car_plate_number)
  print("Number of overspeed :", count_overspeed)
  print("Total time of overspeed :", time_overspeed)

  print("Number of fatigue driving :",count_fatigueDriving)

  print("Number of neutral slide :", count_neutralSlide)
  print("Time of neutral slide :", time_neutralSlide)

  print("Number of rapidly speed changing : ",count_rapidSpeedUp+count_rapidSlowDown, f"({count_rapidSpeedUp} speedup + {count_rapidSlowDown} slowdowm)")
  print("Number of Hthrottle Stop : ", count_hthrottleStop)
  print("Number of oil Leak : ", count_oilLeak)

  print("\nTotal number of dangerous events : " , count_dangerEvent)
  print("---------------------------------------------------------------")





name_list = df_count.select("DriverID").rdd.map(lambda x: x[0]).collect()
for i in range(len(name_list)):
  printPersonInfo(df,name_list[i])
  if i == 3: 
    break


